
import DB.adminConnection;
import java.awt.Color;
import java.sql.DriverManager;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Ndapanda Mutatabikwa
 */
public class TicketBooking extends javax.swing.JFrame {

    /**
     * Creates new form TicketBooking
     */
    public TicketBooking() {
        initComponents();
        tableViewFlight();
    }

    Connection connect = null;
    PreparedStatement pst = null;
    Statement st = null;
    ResultSet rs = null;
    private JFrame admin;
    String urllink = "jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=Flight_Management;encrypt=true;trustServerCertificate=true;";
    String pass = "35987521456";
    String username = "adnim";

    private void tableViewFlight() {

        adminConnection adminConn = new adminConnection();
        adminConn.getFlightValues(infoTable, "");
        DefaultTableModel model = (DefaultTableModel) infoTable.getModel();

        infoTable.setRowHeight(30);
        infoTable.setShowGrid(true);
        infoTable.setGridColor(Color.black); // Use Color.black instead of black
        infoTable.setBackground(Color.white); // Use Color.white instead of white

    }

    public boolean isEmptyFlight() {

        if (firstName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Your firstname is missing!.");
            return false;
        }
        if (lastName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "your lastname is missing!.");
            return false;
        }
        if (passport.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Your passport is missing!.");
        }

        return true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passportNumber = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        flightName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        flightDate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        arrivalDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Submit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        passport = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        passportNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passportNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportNumberActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Ticket Booking ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 28, 255, -1));

        jLabel4.setText("CustomerID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel5.setText("FirstName:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        jLabel7.setText("LastName:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Flight Details:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 220, 100, -1));

        jLabel9.setText("FlightName:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        flightName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        flightName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightNameActionPerformed(evt);
            }
        });
        jPanel1.add(flightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 185, 36));

        jLabel10.setText("Departure Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 90, -1));

        flightDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        flightDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightDateActionPerformed(evt);
            }
        });
        jPanel1.add(flightDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 186, 35));

        jLabel16.setText("Arrival Date:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        arrivalDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(arrivalDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 186, 36));

        jLabel11.setText("Price:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 43, -1));

        price.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 186, 36));

        jLabel12.setText("Seats:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 43, -1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 74, 30));

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, -1, 36));

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, 36));

        jLabel2.setText("Departure Airport");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, -1));

        jLabel3.setText("Arrival Airport");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 80, -1));

        infoTable.setBorder(new javax.swing.border.MatteBorder(null));
        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Departure Airport", "Arrival Airport", "Departure Date", "Departure Time", "Arrival Date", "Arrival Time", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(infoTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 520, 250));
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 180, 30));
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 180, 30));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 150, 200, 30));
        jPanel1.add(passport, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 92, 180, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AirPlaneWing_1.jpeg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (JOptionPane.showConfirmDialog(admin, "Are you sure,you want to exit?", "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
 if (isEmptyFlight()) {
    try {
        // Fetch input values from UI components
        String pass = passport.getText();
        String firstname = firstName.getText();
        String lastname = lastName.getText();
        String flightnumber = flightName.getText();
        String departureAirport = jTextField2.getText();
        String arrivalAirport = jTextField3.getText();
        String departureDate = flightDate.getText();
        String arrivaldate = arrivalDate.getText();
        String priceTicketText = price.getText();
        String seat = String.valueOf(jSpinner1.getValue()); // Safe conversion to String

        // Parse the price into an integer
        int ticketPrice = Integer.parseInt(priceTicketText);
        
        // Create connection object and book ticket
        TicketBookingConnectino ticketBooking = new TicketBookingConnectino();
        ticketBooking.bookingTicket(flightnumber, firstname, lastname, flightnumber, departureAirport, arrivalAirport, departureDate, arrivaldate, ticketPrice, seat);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid price format. Please enter a valid price.");
    } catch (NullPointerException npe) {
        JOptionPane.showMessageDialog(this, "Please ensure all fields are filled correctly.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
    }
}


    }//GEN-LAST:event_SubmitActionPerformed

    private void flightDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightDateActionPerformed

    private void flightNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightNameActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void infoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) infoTable.getModel();
        int rowIndex = infoTable.getSelectedRow();
        if (rowIndex != -1) { // Check if a row is selected
            flightName.setText(model.getValueAt(rowIndex, 0).toString());
            jTextField2.setText(model.getValueAt(rowIndex, 1).toString());
            jTextField3.setText(model.getValueAt(rowIndex, 2).toString());

            price.setText(model.getValueAt(rowIndex, 7).toString());
            try {

                flightDate.setText(model.getValueAt(rowIndex, 5).toString());

                arrivalDate.setText(model.getValueAt(rowIndex, 3).toString());

            } catch (NumberFormatException ex) {
                // Handle parsing exceptions
                java.util.logging.Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_infoTableMouseClicked

    private void passportNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passportNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField arrivalDate;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField flightDate;
    private javax.swing.JTextField flightName;
    private javax.swing.JTable infoTable;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField passport;
    private javax.swing.JTextField passportNumber;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
